version: '3'
services:
  db:
    image: microsoft/mssql-server-linux
    ports:
    - "1435:1433"
    volumes:
    - data:/var/opt/mssql/data
    environment:
    - SA_PASSWORD=M!gr@+|0n5
    - ACCEPT_EULA=Y
volumes:
  data: